export interface PropFirm {
    id: string
    name: string
    slug: string
    logo: string
    rating: number
    reviewCount: number
    maxFunding: string
    profitSplit: string
    evaluationType: "1-Step" | "2-Step" | "Instant"
    priceStarting: number
    features: string[]
    description: string
    pros: string[]
    cons: string[]
    fullReview: string
    affiliateUrl: string
    websiteUrl: string
    metaTitle: string
    metaDescription: string
    hiddenRules: string[]
    spreadType: string
}

export const firms: PropFirm[] = [
    {
        id: "1",
        name: "FTMO",
        slug: "ftmo",
        logo: "/logos/ftmo.png",
        rating: 4.9,
        reviewCount: 1250,
        maxFunding: "$200,000",
        profitSplit: "Up to 90%",
        evaluationType: "2-Step",
        priceStarting: 164,
        features: ["Trusted since 2015", "Bi-weekly Payouts", "Free Trial"],
        description: "The industry leader in proprietary trading. FTMO offers a robust 2-step evaluation process with excellent support and reliable payouts.",
        pros: ["Industry standard reliability", "Great trading conditions", "Free trial available", "Fast payouts"],
        cons: ["Stricter drawdown rules than some competitors", "Weekend holding restrictions on some accounts"],
        fullReview: "FTMO is widely considered the gold standard in the prop trading industry. Established in 2015, they have paid out millions to traders worldwide. Their evaluation process consists of a Challenge and Verification stage. Once funded, traders can keep up to 90% of their profits. The trading conditions are excellent, with low spreads and fast execution. Customer support is top-notch, available 24/7 in multiple languages.",
        affiliateUrl: "https://ftmo.com/en/",
        websiteUrl: "https://ftmo.com/en/",
        metaTitle: "FTMO Review 2025: Is it Still the Best Prop Firm?",
        metaDescription: "Read our in-depth FTMO review. We analyze their funding challenges, profit splits, and payout reliability to help you decide if they are the right prop firm for you.",
        hiddenRules: ["Strict news trading rules on Swing accounts", "2-minute buffer around high-impact news events", "Maximum position hold time during news windows"],
        spreadType: "Raw + Commission"
    },
    {
        id: "2",
        name: "The 5%ers",
        slug: "the-5ers",
        logo: "/logos/5ers.png",
        rating: 4.8,
        reviewCount: 850,
        maxFunding: "$4,000,000",
        profitSplit: "Up to 100%",
        evaluationType: "Instant",
        priceStarting: 260,
        features: ["Instant Funding", "Scale up to $4M", "Salary Program"],
        description: "Unique instant funding model that allows you to start trading with real capital immediately. Great for traders who want to skip the challenge.",
        pros: ["Instant funding (no evaluation)", "High scaling potential", "Salary for top traders", "Long time in business"],
        cons: ["Lower leverage (1:10 to 1:30)", "Higher entry cost for instant funding"],
        fullReview: "The 5%ers offer a unique proposition: instant funding. Unlike most firms that require you to pass a challenge, The 5%ers give you a funded account immediately. You start with a smaller capital and scale up as you make profits. They offer a hyper-growth program that can scale up to $4 million. The trade-off is lower leverage and a higher initial fee compared to challenge-based firms, but for traders who want to start earning immediately, it's an excellent choice.",
        affiliateUrl: "https://the5ers.com/",
        websiteUrl: "https://the5ers.com/",
        metaTitle: "The 5%ers Review: Instant Funding Prop Firm Explained",
        metaDescription: "Detailed review of The 5%ers instant funding program. Learn how to get funded immediately without a challenge and scale up to $4 million.",
        hiddenRules: ["High Stakes limit requires stoploss on every trade", "Mandatory stop-loss on all positions", "Daily loss limit strictly enforced at equity level"],
        spreadType: "Raw Spreads"
    },
    {
        id: "3",
        name: "FundedNext",
        slug: "fundednext",
        logo: "/logos/fundednext.png",
        rating: 4.8,
        reviewCount: 1100,
        maxFunding: "$300,000",
        profitSplit: "Up to 95%",
        evaluationType: "1-Step",
        priceStarting: 99,
        features: ["15% Profit Share in Challenge", "No Time Limit", "Balance Based Drawdown"],
        description: "One of the few firms that pays you a profit share even during the challenge phase. Offers flexible trading rules and competitive pricing.",
        pros: ["Profit share during challenge", "No time limits", "Balance-based drawdown", "Low starting price"],
        cons: ["Complex rule set for some accounts", "Newer in the market"],
        fullReview: "FundedNext disrupted the industry by introducing profit sharing during the challenge phase. This means you can earn money while you are still being evaluated. They offer both 1-step and 2-step models with no time limits. Their balance-based drawdown is also more trader-friendly than the equity-based drawdown used by many competitors.",
        affiliateUrl: "https://fundednext.com/",
        websiteUrl: "https://fundednext.com/",
        metaTitle: "FundedNext Review 2025: Profit Share During Challenge?",
        metaDescription: "FundedNext pays you while you trade. Read our review of their unique profit-sharing model and balance-based drawdown rules.",
        hiddenRules: ["IP address consistency is strictly monitored", "VPN usage may trigger account review", "Geographic location changes require notification"],
        spreadType: "Low Spreads"
    },
    {
        id: "4",
        name: "Alpha Capital Group",
        slug: "alpha-capital",
        logo: "/logos/alpha.png",
        rating: 4.7,
        reviewCount: 620,
        maxFunding: "$2,000,000",
        profitSplit: "80%",
        evaluationType: "2-Step",
        priceStarting: 497,
        features: ["0% Commission", "Raw Spreads", "Dashboard 2.0"],
        description: "Built by traders for traders. Alpha Capital Group offers competitive trading conditions and a custom-built dashboard for analytics.",
        pros: ["0% commission on trades", "Excellent dashboard", "Good educational resources", "Responsive support"],
        cons: ["Newer than FTMO", "Limited platform options"],
        fullReview: "Alpha Capital Group has quickly made a name for itself by offering 0% commission trading, which is a huge advantage for scalpers and high-frequency traders. Their custom dashboard provides detailed analytics to help you improve your trading. The evaluation is a standard 2-step process. They are praised for their transparency and community engagement.",
        affiliateUrl: "https://alphacapitalgroup.uk/",
        websiteUrl: "https://alphacapitalgroup.uk/",
        metaTitle: "Alpha Capital Group Review: 0% Commission Prop Trading",
        metaDescription: "Is Alpha Capital Group legit? We review their 0% commission trading accounts, spreads, and payout process.",
        hiddenRules: ["Martingale strategies are banned", "Grid trading with increasing lot sizes prohibited", "Maximum of 3x position scaling allowed"],
        spreadType: "Raw Spreads"
    },
    {
        id: "5",
        name: "E8 Markets",
        slug: "e8-markets",
        logo: "/logos/e8.png",
        rating: 4.7,
        reviewCount: 580,
        maxFunding: "$2,400,000",
        profitSplit: "80%",
        evaluationType: "1-Step",
        priceStarting: 228,
        features: ["Scale up to $2.4M", "80% Profit Split", "ELEV8 Program"],
        description: "E8 Markets offers one of the highest scaling potentials in the industry with their ELEV8 program that can take you to $2.4M in funded capital.",
        pros: ["Highest scaling potential", "Simple 1-step evaluation", "Fair trading rules", "Regular promotions"],
        cons: ["Strict lot size limits", "Support can be slow during peak times"],
        fullReview: "E8 Markets has become a favorite among traders looking for high scaling potential. Their ELEV8 program is one of the most generous in the industry, allowing traders to scale up to $2.4 million. The 1-step evaluation is straightforward, and their rules are fair compared to many competitors. They frequently run promotions and discounts.",
        affiliateUrl: "https://e8markets.com/",
        websiteUrl: "https://e8markets.com/",
        metaTitle: "E8 Markets Review: Scale to $2.4M with ELEV8 Program",
        metaDescription: "E8 Markets review covering their ELEV8 scaling program, evaluation process, and trading conditions. Is it worth the investment?",
        hiddenRules: ["Maximum open lots limit based on equity", "Position sizing capped at 1 lot per $10k equity", "Aggregate position limits apply across all pairs"],
        spreadType: "Low Spreads"
    },
    {
        id: "6",
        name: "FundingPips",
        slug: "fundingpips",
        logo: "/logos/fundingpips.png",
        rating: 4.6,
        reviewCount: 450,
        maxFunding: "$300,000",
        profitSplit: "Up to 90%",
        evaluationType: "2-Step",
        priceStarting: 59,
        features: ["Weekly Payouts", "Lowest Prices", "No Time Limit"],
        description: "One of the most affordable prop firms offering weekly payouts and competitive profit splits. Great for traders on a budget.",
        pros: ["Weekly payout option", "Very affordable", "No time limits", "Simple rules"],
        cons: ["Smaller max funding than competitors", "Limited instruments"],
        fullReview: "FundingPips has carved out a niche as one of the most affordable prop firms in the market. Their weekly payout option is a standout feature for traders who want quick access to their profits. The evaluation process is straightforward with no time limits, and their rules are trader-friendly.",
        affiliateUrl: "https://fundingpips.com/",
        websiteUrl: "https://fundingpips.com/",
        metaTitle: "FundingPips Review: Weekly Payouts & Low Prices",
        metaDescription: "FundingPips offers weekly payouts and some of the lowest prices in the industry. Read our complete review.",
        hiddenRules: ["5% profit rule required for payouts", "Must hit 5% before requesting payout", "Partial withdrawals have minimum thresholds"],
        spreadType: "Standard Spreads"
    },
    {
        id: "7",
        name: "Blue Guardian",
        slug: "blue-guardian",
        logo: "/logos/blueguardian.png",
        rating: 4.6,
        reviewCount: 400,
        maxFunding: "$2,000,000",
        profitSplit: "85%",
        evaluationType: "2-Step",
        priceStarting: 187,
        features: ["Guardian Protector", "No Time Limits", "Bi-weekly Payouts"],
        description: "Known for their 'Guardian Protector' tool which helps prevent hitting the daily drawdown limit.",
        pros: ["Guardian Protector tool", "No time limits", "Simple rules", "Good scaling plan"],
        cons: ["Slippage can be high during news", "Support response time varies"],
        fullReview: "Blue Guardian is famous for its 'Guardian Protector' feature, a built-in risk management tool that helps traders avoid hitting their daily loss limit. This is invaluable for newer traders. They offer a straightforward 2-step evaluation with no time limits and bi-weekly payouts. The scaling plan allows you to double your account size every few months if you are profitable.",
        affiliateUrl: "https://blueguardian.com/",
        websiteUrl: "https://blueguardian.com/",
        metaTitle: "Blue Guardian Review: The Best Prop Firm for Risk Management?",
        metaDescription: "Review of Blue Guardian's 'Guardian Protector' tool and funding programs. See if their risk management features can help you pass.",
        hiddenRules: ["Slippage on news can be significant", "Execution delays during high volatility", "Stop losses may experience 2-5 pip slippage"],
        spreadType: "Variable Spreads"
    },
    {
        id: "8",
        name: "TopTier Trader",
        slug: "toptier-trader",
        logo: "/logos/toptier.png",
        rating: 4.5,
        reviewCount: 350,
        maxFunding: "$600,000",
        profitSplit: "Up to 90%",
        evaluationType: "2-Step",
        priceStarting: 149,
        features: ["Swing Trading Allowed", "Scaling Plan", "Regular Promos"],
        description: "A reliable firm offering standard 2-step challenges with competitive pricing and regular promotional offers.",
        pros: ["Swing trading friendly", "Regular discounts", "Clear rules", "Fast verification"],
        cons: ["High spreads on some pairs", "Strict news trading rules on some accounts"],
        fullReview: "TopTier Trader is a solid choice for swing traders as they allow holding trades over the weekend. They frequently run promotions offering discounts and higher profit splits. The evaluation is a standard 2-step process. They have a good reputation for payouts and fair treatment of traders.",
        affiliateUrl: "https://toptiertrader.com/",
        websiteUrl: "https://toptiertrader.com/",
        metaTitle: "TopTier Trader Review: Swing Trading Friendly Prop Firm",
        metaDescription: "TopTier Trader review for 2025. We analyze their swing trading rules, scaling plan, and payout history.",
        hiddenRules: ["No weekend holding on regular accounts", "Friday close-out required for standard accounts", "Swing accounts available at premium"],
        spreadType: "Standard Spreads"
    },
    {
        id: "9",
        name: "Maven Trading",
        slug: "maven-trading",
        logo: "/logos/maven.png",
        rating: 4.5,
        reviewCount: 320,
        maxFunding: "$400,000",
        profitSplit: "80%",
        evaluationType: "1-Step",
        priceStarting: 99,
        features: ["No Time Limit", "Low Reset Fees", "True ECN Execution"],
        description: "Maven Trading offers true ECN execution with no time limits and the cheapest reset fees in the industry.",
        pros: ["True ECN execution", "Cheapest reset fees", "No time limits", "Straightforward rules"],
        cons: ["Lower profit split", "Smaller community"],
        fullReview: "Maven Trading focuses on providing the best trading conditions with true ECN execution. Their standout feature is having the cheapest reset fees in the industry, making it easier for traders to have multiple attempts at passing the evaluation. The 1-step process is simple, and there are no time limits.",
        affiliateUrl: "https://maventrading.com/",
        websiteUrl: "https://maventrading.com/",
        metaTitle: "Maven Trading Review: True ECN Execution & Low Reset Fees",
        metaDescription: "Maven Trading offers true ECN execution and the cheapest reset fees. Read our complete review of this growing prop firm.",
        hiddenRules: ["Cheapest reset fees in industry at $25", "Reset preserves account history", "Multiple resets may trigger review"],
        spreadType: "ECN Raw"
    },
    {
        id: "10",
        name: "MyFundedFX",
        slug: "myfundedfx",
        logo: "/logos/myfundedfx.png",
        rating: 4.4,
        reviewCount: 290,
        maxFunding: "$600,000",
        profitSplit: "80%",
        evaluationType: "1-Step",
        priceStarting: 129,
        features: ["Crypto Trading", "Weekend Holding", "No Lot Limits"],
        description: "One of the few prop firms offering cryptocurrency trading alongside forex. Weekend holding and no lot size limits make it versatile.",
        pros: ["Crypto trading available", "No lot size limits", "Weekend holding allowed", "Competitive pricing"],
        cons: ["High slippage on exotic pairs", "Customer support needs improvement"],
        fullReview: "MyFundedFX stands out by offering cryptocurrency trading alongside traditional forex pairs. This is rare in the prop firm industry. They also allow weekend holding and have no lot size limits, giving traders maximum flexibility. The 1-step evaluation is quick and straightforward.",
        affiliateUrl: "https://myfundedfx.com/",
        websiteUrl: "https://myfundedfx.com/",
        metaTitle: "MyFundedFX Review: The Best Prop Firm for Crypto Trading?",
        metaDescription: "MyFundedFX offers cryptocurrency trading and no lot limits. Is it the right prop firm for you? Read our detailed review.",
        hiddenRules: ["High slippage on exotic pairs reported", "Crypto spreads widen significantly on weekends", "Maximum 10% of balance in crypto positions"],
        spreadType: "Variable Spreads"
    },
    {
        id: "11",
        name: "Smart Prop Trader",
        slug: "smart-prop-trader",
        logo: "/logos/smartprop.png",
        rating: 4.4,
        reviewCount: 270,
        maxFunding: "$400,000",
        profitSplit: "85%",
        evaluationType: "2-Step",
        priceStarting: 79,
        features: ["Lowest Prices", "Bi-weekly Payouts", "Simple Rules"],
        description: "Smart Prop Trader offers some of the lowest prices in the industry while maintaining competitive profit splits and fair rules.",
        pros: ["Very affordable", "Simple clear rules", "Fast payouts", "Good customer support"],
        cons: ["Strict consistency rule", "Lower max funding"],
        fullReview: "Smart Prop Trader has positioned itself as the budget-friendly option without sacrificing quality. Their prices are among the lowest in the industry, making it accessible for new traders. The rules are simple and transparent, and payouts are processed bi-weekly without issues.",
        affiliateUrl: "https://smartproptrader.com/",
        websiteUrl: "https://smartproptrader.com/",
        metaTitle: "Smart Prop Trader Review: The Most Affordable Prop Firm?",
        metaDescription: "Smart Prop Trader offers the lowest prices in the industry. But is cheap always good? Read our complete analysis.",
        hiddenRules: ["Strict consistency rule on payouts", "No single day can exceed 50% of total profits", "Winning days must be distributed evenly"],
        spreadType: "Standard Spreads"
    },
    {
        id: "12",
        name: "Instant Funding",
        slug: "instant-funding",
        logo: "/logos/instantfunding.png",
        rating: 4.3,
        reviewCount: 240,
        maxFunding: "$200,000",
        profitSplit: "80%",
        evaluationType: "Instant",
        priceStarting: 445,
        features: ["No Evaluation", "Trade Immediately", "Weekly Payouts"],
        description: "Skip the challenge entirely and start trading with funded capital immediately. Higher entry cost but instant access to profits.",
        pros: ["No evaluation required", "Start trading immediately", "Weekly payouts", "No time pressure"],
        cons: ["Higher initial cost", "Higher spreads than evaluation firms"],
        fullReview: "Instant Funding does exactly what the name suggests - you get funded immediately without any evaluation. This is perfect for experienced traders who are confident in their strategy and don't want to spend weeks proving themselves. The trade-off is a higher entry cost and slightly higher spreads, but for many traders, the immediate access to funded capital is worth it.",
        affiliateUrl: "https://instantfunding.io/",
        websiteUrl: "https://instantfunding.io/",
        metaTitle: "Instant Funding Review: Trade Funded Capital Immediately",
        metaDescription: "Instant Funding lets you skip the challenge and trade real capital immediately. Is it worth the premium? Read our review.",
        hiddenRules: ["Higher spreads than evaluation firms (0.5-1 pip add-on)", "Commission-free but built into spread", "Maximum 5% daily drawdown strictly enforced"],
        spreadType: "Spread Markup"
    }
]
