export interface PropFirm {
    id: string
    name: string
    slug: string
    logo: string
    rating: number
    reviewCount: number
    maxFunding: string
    profitSplit: string
    evaluationType: "1-Step" | "2-Step" | "Instant"
    priceStarting: number
    features: string[]
    description: string
    pros: string[]
    cons: string[]
    fullReview: string
    affiliateUrl: string
    websiteUrl: string
    metaTitle: string
    metaDescription: string
    hiddenRules: string[]
    spreadType: string
}

export const firms: PropFirm[] = [
    {
        id: "1",
        name: "FTMO",
        slug: "ftmo",
        logo: "/logos/ftmo.png",
        rating: 4.9,
        reviewCount: 1250,
        maxFunding: "$200,000",
        profitSplit: "Up to 90%",
        evaluationType: "2-Step",
        priceStarting: 164,
        features: ["Trusted since 2015", "Bi-weekly Payouts", "Free Trial"],
        description: "The industry leader in proprietary trading. FTMO offers a robust 2-step evaluation process with excellent support and reliable payouts.",
        pros: ["Industry standard reliability", "Great trading conditions", "Free trial available", "Fast payouts"],
        cons: ["Stricter drawdown rules than some competitors", "Weekend holding restrictions on some accounts"],
        fullReview: "FTMO is widely considered the gold standard in the prop trading industry. Established in 2015, they have paid out millions to traders worldwide. Their evaluation process consists of a Challenge and Verification stage. Once funded, traders can keep up to 90% of their profits. The trading conditions are excellent, with low spreads and fast execution. Customer support is top-notch, available 24/7 in multiple languages.",
        affiliateUrl: "https://ftmo.com/en/",
        websiteUrl: "https://ftmo.com/en/",
        metaTitle: "FTMO Review 2025: Is it Still the Best Prop Firm?",
        metaDescription: "Read our in-depth FTMO review. We analyze their funding challenges, profit splits, and payout reliability to help you decide if they are the right prop firm for you.",
        hiddenRules: ["Strict news trading rules on Swing accounts", "2-minute buffer around high-impact news events", "Maximum position hold time during news windows"],
        spreadType: "Raw + Commission"
    },
    {
        id: "2",
        name: "The 5%ers",
        slug: "the-5ers",
        logo: "/logos/5ers.png",
        rating: 4.8,
        reviewCount: 850,
        maxFunding: "$4,000,000",
        profitSplit: "Up to 100%",
        evaluationType: "Instant",
        priceStarting: 260,
        features: ["Instant Funding", "Scale up to $4M", "Salary Program"],
        description: "Unique instant funding model that allows you to start trading with real capital immediately. Great for traders who want to skip the challenge.",
        pros: ["Instant funding (no evaluation)", "High scaling potential", "Salary for top traders", "Long time in business"],
        cons: ["Lower leverage (1:10 to 1:30)", "Higher entry cost for instant funding"],
        fullReview: "The 5%ers offer a unique proposition: instant funding. Unlike most firms that require you to pass a challenge, The 5%ers give you a funded account immediately. You start with a smaller capital and scale up as you make profits. They offer a hyper-growth program that can scale up to $4 million. The trade-off is lower leverage and a higher initial fee compared to challenge-based firms, but for traders who want to start earning immediately, it's an excellent choice.",
        affiliateUrl: "https://the5ers.com/",
        websiteUrl: "https://the5ers.com/",
        metaTitle: "The 5%ers Review: Instant Funding Prop Firm Explained",
        metaDescription: "Detailed review of The 5%ers instant funding program. Learn how to get funded immediately without a challenge and scale up to $4 million.",
        hiddenRules: ["High Stakes limit requires stoploss on every trade", "Mandatory stop-loss on all positions", "Daily loss limit strictly enforced at equity level"],
        spreadType: "Raw Spreads"
    },
    {
        id: "3",
        name: "FundedNext",
        slug: "fundednext",
        logo: "/logos/fundednext.png",
        rating: 4.8,
        reviewCount: 1100,
        maxFunding: "$300,000",
        profitSplit: "Up to 95%",
        evaluationType: "1-Step",
        priceStarting: 99,
        features: ["15% Profit Share in Challenge", "No Time Limit", "Balance Based Drawdown"],
        description: "One of the few firms that pays you a profit share even during the challenge phase. Offers flexible trading rules and competitive pricing.",
        pros: ["Profit share during challenge", "No time limits", "Balance-based drawdown", "Low starting price"],
        cons: ["Complex rule set for some accounts", "Newer in the market"],
        fullReview: "FundedNext disrupted the industry by introducing profit sharing during the challenge phase. This means you can earn money while you are still being evaluated. They offer both 1-step and 2-step models with no time limits. Their balance-based drawdown is also more trader-friendly than the equity-based drawdown used by many competitors.",
        affiliateUrl: "https://fundednext.com/",
        websiteUrl: "https://fundednext.com/",
        metaTitle: "FundedNext Review 2025: Profit Share During Challenge?",
        metaDescription: "FundedNext pays you while you trade. Read our review of their unique profit-sharing model and balance-based drawdown rules.",
        hiddenRules: ["IP address consistency is strictly monitored", "VPN usage may trigger account review", "Geographic location changes require notification"],
        spreadType: "Low Spreads"
    },
    {
        id: "4",
        name: "Alpha Capital Group",
        slug: "alpha-capital",
        logo: "/logos/alpha.png",
        rating: 4.7,
        reviewCount: 620,
        maxFunding: "$2,000,000",
        profitSplit: "80%",
        evaluationType: "2-Step",
        priceStarting: 497,
        features: ["0% Commission", "Raw Spreads", "Dashboard 2.0"],
        description: "Built by traders for traders. Alpha Capital Group offers competitive trading conditions and a custom-built dashboard for analytics.",
        pros: ["0% commission on trades", "Excellent dashboard", "Good educational resources", "Responsive support"],
        cons: ["Newer than FTMO", "Limited platform options"],
        fullReview: "Alpha Capital Group has quickly made a name for itself by offering 0% commission trading, which is a huge advantage for scalpers and high-frequency traders. Their custom dashboard provides detailed analytics to help you improve your trading. The evaluation is a standard 2-step process. They are praised for their transparency and community engagement.",
        affiliateUrl: "https://alphacapitalgroup.uk/",
        websiteUrl: "https://alphacapitalgroup.uk/",
        metaTitle: "Alpha Capital Group Review: 0% Commission Prop Trading",
        metaDescription: "Is Alpha Capital Group legit? We review their 0% commission trading accounts, spreads, and payout process.",
        hiddenRules: ["Martingale strategies are banned", "Grid trading with increasing lot sizes prohibited", "Maximum of 3x position scaling allowed"],
        spreadType: "Raw Spreads"
    },
    {
        id: "5",
        name: "E8 Markets",
        slug: "e8-markets",
        logo: "/logos/e8.png",
        rating: 4.7,
        reviewCount: 580,
        maxFunding: "$2,400,000",
        profitSplit: "80%",
        evaluationType: "1-Step",
        priceStarting: 228,
        features: ["Scale up to $2.4M", "80% Profit Split", "ELEV8 Program"],
        description: "E8 Markets offers one of the highest scaling potentials in the industry with their ELEV8 program that can take you to $2.4M in funded capital.",
        pros: ["Highest scaling potential", "Simple 1-step evaluation", "Fair trading rules", "Regular promotions"],
        cons: ["Strict lot size limits", "Support can be slow during peak times"],
        fullReview: "E8 Markets has become a favorite among traders looking for high scaling potential. Their ELEV8 program is one of the most generous in the industry, allowing traders to scale up to $2.4 million. The 1-step evaluation is straightforward, and their rules are fair compared to many competitors. They frequently run promotions and discounts.",
        affiliateUrl: "https://e8markets.com/",
        websiteUrl: "https://e8markets.com/",
        metaTitle: "E8 Markets Review: Scale to $2.4M with ELEV8 Program",
        metaDescription: "E8 Markets review covering their ELEV8 scaling program, evaluation process, and trading conditions. Is it worth the investment?",
        hiddenRules: ["Maximum open lots limit based on equity", "Position sizing capped at 1 lot per $10k equity", "Aggregate position limits apply across all pairs"],
        spreadType: "Low Spreads"
    },
    {
        id: "6",
        name: "FundingPips",
        slug: "fundingpips",
        logo: "/logos/fundingpips.png",
        rating: 4.6,
        reviewCount: 450,
        maxFunding: "$300,000",
        profitSplit: "Up to 90%",
        evaluationType: "2-Step",
        priceStarting: 59,
        features: ["Weekly Payouts", "Lowest Prices", "No Time Limit"],
        description: "One of the most affordable prop firms offering weekly payouts and competitive profit splits. Great for traders on a budget.",
        pros: ["Weekly payout option", "Very affordable", "No time limits", "Simple rules"],
        cons: ["Smaller max funding than competitors", "Limited instruments"],
        fullReview: "FundingPips has carved out a niche as one of the most affordable prop firms in the market. Their weekly payout option is a standout feature for traders who want quick access to their profits. The evaluation process is straightforward with no time limits, and their rules are trader-friendly.",
        affiliateUrl: "https://fundingpips.com/",
        websiteUrl: "https://fundingpips.com/",
        metaTitle: "FundingPips Review: Weekly Payouts & Low Prices",
        metaDescription: "FundingPips offers weekly payouts and some of the lowest prices in the industry. Read our complete review.",
        hiddenRules: ["5% profit rule required for payouts", "Must hit 5% before requesting payout", "Partial withdrawals have minimum thresholds"],
        spreadType: "Standard Spreads"
    },
    {
        id: "7",
        name: "Blue Guardian",
        slug: "blue-guardian",
        logo: "/logos/blueguardian.png",
        rating: 4.6,
        reviewCount: 400,
        maxFunding: "$2,000,000",
        profitSplit: "85%",
        evaluationType: "2-Step",
        priceStarting: 187,
        features: ["Guardian Protector", "No Time Limits", "Bi-weekly Payouts"],
        description: "Known for their 'Guardian Protector' tool which helps prevent hitting the daily drawdown limit.",
        pros: ["Guardian Protector tool", "No time limits", "Simple rules", "Good scaling plan"],
        cons: ["Slippage can be high during news", "Support response time varies"],
        fullReview: "Blue Guardian is famous for its 'Guardian Protector' feature, a built-in risk management tool that helps traders avoid hitting their daily loss limit. This is invaluable for newer traders. They offer a straightforward 2-step evaluation with no time limits and bi-weekly payouts. The scaling plan allows you to double your account size every few months if you are profitable.",
        affiliateUrl: "https://blueguardian.com/",
        websiteUrl: "https://blueguardian.com/",
        metaTitle: "Blue Guardian Review: The Best Prop Firm for Risk Management?",
        metaDescription: "Review of Blue Guardian's 'Guardian Protector' tool and funding programs. See if their risk management features can help you pass.",
        hiddenRules: ["Slippage on news can be significant", "Execution delays during high volatility", "Stop losses may experience 2-5 pip slippage"],
        spreadType: "Variable Spreads"
    },
    {
        id: "8",
        name: "TopTier Trader",
        slug: "toptier-trader",
        logo: "/logos/toptier.png",
        rating: 4.5,
        reviewCount: 350,
        maxFunding: "$600,000",
        profitSplit: "Up to 90%",
        evaluationType: "2-Step",
        priceStarting: 149,
        features: ["Swing Trading Allowed", "Scaling Plan", "Regular Promos"],
        description: "A reliable firm offering standard 2-step challenges with competitive pricing and regular promotional offers.",
        pros: ["Swing trading friendly", "Regular discounts", "Clear rules", "Fast verification"],
        cons: ["High spreads on some pairs", "Strict news trading rules on some accounts"],
        fullReview: "TopTier Trader is a solid choice for swing traders as they allow holding trades over the weekend. They frequently run promotions offering discounts and higher profit splits. The evaluation is a standard 2-step process. They have a good reputation for payouts and fair treatment of traders.",
        affiliateUrl: "https://toptiertrader.com/",
        websiteUrl: "https://toptiertrader.com/",
        metaTitle: "TopTier Trader Review: Swing Trading Friendly Prop Firm",
        metaDescription: "TopTier Trader review for 2025. We analyze their swing trading rules, scaling plan, and payout history.",
        hiddenRules: ["No weekend holding on regular accounts", "Friday close-out required for standard accounts", "Swing accounts available at premium"],
        spreadType: "Standard Spreads"
    },
    {
        id: "9",
        name: "Maven Trading",
        slug: "maven-trading",
        logo: "/logos/maven.png",
        rating: 4.5,
        reviewCount: 320,
        maxFunding: "$400,000",
        profitSplit: "80%",
        evaluationType: "1-Step",
        priceStarting: 99,
        features: ["No Time Limit", "Low Reset Fees", "True ECN Execution"],
        description: "Maven Trading offers true ECN execution with no time limits and the cheapest reset fees in the industry.",
        pros: ["True ECN execution", "Cheapest reset fees", "No time limits", "Straightforward rules"],
        cons: ["Lower profit split", "Smaller community"],
        fullReview: "Maven Trading focuses on providing the best trading conditions with true ECN execution. Their standout feature is having the cheapest reset fees in the industry, making it easier for traders to have multiple attempts at passing the evaluation. The 1-step process is simple, and there are no time limits.",
        affiliateUrl: "https://maventrading.com/",
        websiteUrl: "https://maventrading.com/",
        metaTitle: "Maven Trading Review: True ECN Execution & Low Reset Fees",
        metaDescription: "Maven Trading offers true ECN execution and the cheapest reset fees. Read our complete review of this growing prop firm.",
        hiddenRules: ["Cheapest reset fees in industry at $25", "Reset preserves account history", "Multiple resets may trigger review"],
        spreadType: "ECN Raw"
    },
    {
        id: "10",
        name: "MyFundedFX",
        slug: "myfundedfx",
        logo: "/logos/myfundedfx.png",
        rating: 4.4,
        reviewCount: 290,
        maxFunding: "$600,000",
        profitSplit: "80%",
        evaluationType: "1-Step",
        priceStarting: 129,
        features: ["Crypto Trading", "Weekend Holding", "No Lot Limits"],
        description: "One of the few prop firms offering cryptocurrency trading alongside forex. Weekend holding and no lot size limits make it versatile.",
        pros: ["Crypto trading available", "No lot size limits", "Weekend holding allowed", "Competitive pricing"],
        cons: ["High slippage on exotic pairs", "Customer support needs improvement"],
        fullReview: "MyFundedFX stands out by offering cryptocurrency trading alongside traditional forex pairs. This is rare in the prop firm industry. They also allow weekend holding and have no lot size limits, giving traders maximum flexibility. The 1-step evaluation is quick and straightforward.",
        affiliateUrl: "https://myfundedfx.com/",
        websiteUrl: "https://myfundedfx.com/",
        metaTitle: "MyFundedFX Review: The Best Prop Firm for Crypto Trading?",
        metaDescription: "MyFundedFX offers cryptocurrency trading and no lot limits. Is it the right prop firm for you? Read our detailed review.",
        hiddenRules: ["High slippage on exotic pairs reported", "Crypto spreads widen significantly on weekends", "Maximum 10% of balance in crypto positions"],
        spreadType: "Variable Spreads"
    },
    {
        id: "11",
        name: "Smart Prop Trader",
        slug: "smart-prop-trader",
        logo: "/logos/smartprop.png",
        rating: 4.4,
        reviewCount: 270,
        maxFunding: "$400,000",
        profitSplit: "85%",
        evaluationType: "2-Step",
        priceStarting: 79,
        features: ["Lowest Prices", "Bi-weekly Payouts", "Simple Rules"],
        description: "Smart Prop Trader offers some of the lowest prices in the industry while maintaining competitive profit splits and fair rules.",
        pros: ["Very affordable", "Simple clear rules", "Fast payouts", "Good customer support"],
        cons: ["Strict consistency rule", "Lower max funding"],
        fullReview: "Smart Prop Trader has positioned itself as the budget-friendly option without sacrificing quality. Their prices are among the lowest in the industry, making it accessible for new traders. The rules are simple and transparent, and payouts are processed bi-weekly without issues.",
        affiliateUrl: "https://smartproptrader.com/",
        websiteUrl: "https://smartproptrader.com/",
        metaTitle: "Smart Prop Trader Review: The Most Affordable Prop Firm?",
        metaDescription: "Smart Prop Trader offers the lowest prices in the industry. But is cheap always good? Read our complete analysis.",
        hiddenRules: ["Strict consistency rule on payouts", "No single day can exceed 50% of total profits", "Winning days must be distributed evenly"],
        spreadType: "Standard Spreads"
    },
    {
        id: "12",
        name: "Instant Funding",
        slug: "instant-funding",
        logo: "/logos/instantfunding.png",
        rating: 4.3,
        reviewCount: 240,
        maxFunding: "$200,000",
        profitSplit: "80%",
        evaluationType: "Instant",
        priceStarting: 445,
        features: ["No Evaluation", "Trade Immediately", "Weekly Payouts"],
        description: "Skip the challenge entirely and start trading with funded capital immediately. Higher entry cost but instant access to profits.",
        pros: ["No evaluation required", "Start trading immediately", "Weekly payouts", "No time pressure"],
        cons: ["Higher initial cost", "Higher spreads than evaluation firms"],
        fullReview: "Instant Funding does exactly what the name suggests - you get funded immediately without any evaluation. This is perfect for experienced traders who are confident in their strategy and don't want to spend weeks proving themselves. The trade-off is a higher entry cost and slightly higher spreads, but for many traders, the immediate access to funded capital is worth it.",
        affiliateUrl: "https://instantfunding.io/",
        websiteUrl: "https://instantfunding.io/",
        metaTitle: "Instant Funding Review: Trade Funded Capital Immediately",
        metaDescription: "Instant Funding lets you skip the challenge and trade real capital immediately. Is it worth the premium? Read our review.",
        hiddenRules: ["Higher spreads than evaluation firms (0.5-1 pip add-on)", "Commission-free but built into spread", "Maximum 5% daily drawdown strictly enforced"],
        spreadType: "Spread Markup"
    },
    {
        id: "13",
        name: "Apex Trader Funding",
        slug: "apex-trader-funding",
        logo: "/logos/apex.png",
        rating: 4.6,
        reviewCount: 920,
        maxFunding: "$300,000",
        profitSplit: "100%",
        evaluationType: "1-Step",
        priceStarting: 147,
        features: ["100% Profit Split", "Futures Focused", "Frequent Sales"],
        description: "One of the most generous profit splits in the industry at 100%. Specializes in futures trading with regular discount promotions.",
        pros: ["100% profit split", "Regular 80%+ discounts", "Great for futures traders", "Fast evaluation"],
        cons: ["Futures only (no forex)", "Trailing drawdown during evaluation"],
        fullReview: "Apex Trader Funding is a game-changer for futures traders. Unlike most prop firms that take 10-20% of your profits, Apex lets you keep 100%. They frequently run promotions with 80%+ discounts, making their challenges extremely affordable. The evaluation is straightforward with only a 1-step process. The main caveat is that they only offer futures trading, so forex traders will need to look elsewhere.",
        affiliateUrl: "https://apextraderfunding.com/",
        websiteUrl: "https://apextraderfunding.com/",
        metaTitle: "Apex Trader Funding Review: 100% Profit Split Explained",
        metaDescription: "Apex Trader Funding offers 100% profit split for futures traders. Read our complete review of their evaluation process and trading conditions.",
        hiddenRules: ["Trailing drawdown during evaluation locks in losses", "Must trade during US market hours for best execution", "No overnight positions during certain periods"],
        spreadType: "Exchange Fees Only"
    },
    {
        id: "14",
        name: "Topstep",
        slug: "topstep",
        logo: "/logos/topstep.png",
        rating: 4.5,
        reviewCount: 1580,
        maxFunding: "$150,000",
        profitSplit: "90%",
        evaluationType: "2-Step",
        priceStarting: 165,
        features: ["Futures Trading", "Coaching Included", "Well Established"],
        description: "One of the original prop firms in the futures space. Includes coaching and education with all accounts.",
        pros: ["Long track record since 2012", "Excellent education resources", "Professional coaching", "Reliable payouts"],
        cons: ["Futures only", "More expensive than newer competitors", "Stricter rules"],
        fullReview: "Topstep is one of the original proprietary trading firms, founded in 2012. They've funded thousands of traders and have an excellent reputation for reliability. What sets them apart is the education component - all accounts come with access to coaching and trading resources. This makes them ideal for newer traders who want to develop their skills while getting funded.",
        affiliateUrl: "https://topstep.com/",
        websiteUrl: "https://topstep.com/",
        metaTitle: "Topstep Review 2025: Original Futures Prop Firm",
        metaDescription: "Topstep has been funding futures traders since 2012. Read our review of their evaluation, coaching program, and funding options.",
        hiddenRules: ["Trading Combine has strict daily loss limits", "Steps must be passed sequentially", "No trading during certain economic releases"],
        spreadType: "Exchange Fees"
    },
    {
        id: "15",
        name: "Take Profit Trader",
        slug: "take-profit-trader",
        logo: "/logos/tpt.png",
        rating: 4.4,
        reviewCount: 380,
        maxFunding: "$150,000",
        profitSplit: "80%",
        evaluationType: "1-Step",
        priceStarting: 99,
        features: ["Low Cost Entry", "Quick Evaluation", "Futures Trading"],
        description: "Affordable entry into futures prop trading with a simple 1-step evaluation and competitive pricing.",
        pros: ["Very affordable", "Simple evaluation", "Good customer support", "Regular promotions"],
        cons: ["80% profit split", "Futures only", "Smaller maximum funding"],
        fullReview: "Take Profit Trader offers one of the most affordable ways to get into funded futures trading. Their 1-step evaluation is straightforward, and they frequently run promotions that make their already low prices even better. Customer support is responsive and helpful. While the 80% profit split isn't the highest, the low barrier to entry makes them attractive for beginners.",
        affiliateUrl: "https://takeprofittrader.com/",
        websiteUrl: "https://takeprofittrader.com/",
        metaTitle: "Take Profit Trader Review: Affordable Futures Funding",
        metaDescription: "Take Profit Trader offers affordable futures trading evaluations. Read our review of their pricing, rules, and payout process.",
        hiddenRules: ["Trailing drawdown activates after first profit", "No scaling during evaluation", "Specific trading hours required"],
        spreadType: "Exchange Fees"
    },
    {
        id: "16",
        name: "Bulenox",
        slug: "bulenox",
        logo: "/logos/bulenox.png",
        rating: 4.3,
        reviewCount: 290,
        maxFunding: "$250,000",
        profitSplit: "90%",
        evaluationType: "1-Step",
        priceStarting: 115,
        features: ["1-Step Evaluation", "90% Profit Split", "Futures Trading"],
        description: "Fast-growing futures prop firm with a simple 1-step evaluation and competitive 90% profit split.",
        pros: ["Quick 1-step evaluation", "90% profit split", "Affordable pricing", "No minimum trading days"],
        cons: ["Newer company", "Limited track record", "Futures only"],
        fullReview: "Bulenox is a newer entrant in the futures prop trading space but has quickly gained popularity. Their 1-step evaluation is straightforward with no minimum trading days required. The 90% profit split is competitive, and their pricing is affordable. While they lack the track record of established firms, their terms are trader-friendly.",
        affiliateUrl: "https://bulenox.com/",
        websiteUrl: "https://bulenox.com/",
        metaTitle: "Bulenox Review: Fast Futures Funding",
        metaDescription: "Bulenox offers quick 1-step futures evaluations with 90% profit split. Read our complete review.",
        hiddenRules: ["Trailing threshold locks at $100 per contract", "Maximum position limits based on account size", "News trading restrictions apply"],
        spreadType: "Exchange Fees"
    },
    {
        id: "17",
        name: "Earn2Trade",
        slug: "earn2trade",
        logo: "/logos/earn2trade.png",
        rating: 4.4,
        reviewCount: 520,
        maxFunding: "$400,000",
        profitSplit: "80%",
        evaluationType: "2-Step",
        priceStarting: 150,
        features: ["Gauntlet Mini", "Education Focus", "Futures Trading"],
        description: "Education-focused prop firm with their popular Gauntlet Mini program for futures traders.",
        pros: ["Excellent education", "Gauntlet Mini is affordable", "High max funding", "Good for beginners"],
        cons: ["80% profit split", "Futures only", "Longer evaluation process"],
        fullReview: "Earn2Trade is known for their Gauntlet Mini program, which provides an affordable path to funded futures trading. They place a strong emphasis on education and helping traders develop proper skills. Their maximum funding of $400K is among the highest for futures firms. The trade-off is a lower 80% profit split.",
        affiliateUrl: "https://earn2trade.com/",
        websiteUrl: "https://earn2trade.com/",
        metaTitle: "Earn2Trade Review: Gauntlet Mini & Funding Options",
        metaDescription: "Earn2Trade's Gauntlet Mini is one of the most affordable futures evaluations. Read our complete review.",
        hiddenRules: ["Scaling plan has specific profit requirements", "Market hours trading only", "Position limits increase gradually"],
        spreadType: "Exchange Fees"
    },
    {
        id: "18",
        name: "SurgeTrader",
        slug: "surgetrader",
        logo: "/logos/surgetrader.png",
        rating: 4.2,
        reviewCount: 310,
        maxFunding: "$1,000,000",
        profitSplit: "90%",
        evaluationType: "1-Step",
        priceStarting: 250,
        features: ["$1M Max Funding", "1-Step Audition", "Forex & Crypto"],
        description: "High funding potential with their 1-step audition process. Offers forex, indices, and crypto trading.",
        pros: ["$1M max funding", "Simple 1-step process", "Forex and crypto available", "90% profit split"],
        cons: ["Higher entry price", "Newer firm", "10% profit target is high"],
        fullReview: "SurgeTrader offers one of the highest funding amounts in the industry at $1 million. Their 1-step audition process is simpler than traditional 2-step evaluations. They offer forex, indices, and cryptocurrency trading with a 90% profit split. The 10% profit target is higher than some competitors.",
        affiliateUrl: "https://surgetrader.com/",
        websiteUrl: "https://surgetrader.com/",
        metaTitle: "SurgeTrader Review: $1M Funding Potential",
        metaDescription: "SurgeTrader offers up to $1 million in funding. Read our review of their 1-step audition and trading conditions.",
        hiddenRules: ["Consistency rule requires balanced trading", "No trading during high-impact news", "Maximum lot sizes enforced"],
        spreadType: "Raw + Commission"
    },
    {
        id: "19",
        name: "City Traders Imperium",
        slug: "city-traders-imperium",
        logo: "/logos/cti.png",
        rating: 4.5,
        reviewCount: 680,
        maxFunding: "$2,000,000",
        profitSplit: "Up to 100%",
        evaluationType: "2-Step",
        priceStarting: 109,
        features: ["$2M Scaling", "100% Profit Split", "Direct Funding"],
        description: "UK-based prop firm with massive scaling potential up to $2M and 100% profit split for top performers.",
        pros: ["$2M max funding", "100% profit split achievable", "Established UK company", "Direct funding option"],
        cons: ["Complex scaling requirements", "Higher profit targets", "Some restrictions on strategies"],
        fullReview: "City Traders Imperium (CTI) is a well-established UK prop firm offering scaling up to $2 million. What makes them unique is the ability to earn 100% profit split at higher funding levels. They offer both evaluation and direct funding options. CTI is known for their professional approach and reliable payouts.",
        affiliateUrl: "https://citytradersimperium.com/",
        websiteUrl: "https://citytradersimperium.com/",
        metaTitle: "City Traders Imperium Review: Scale to $2M",
        metaDescription: "CTI offers up to $2M funding with 100% profit split. Read our complete review of this UK prop firm.",
        hiddenRules: ["Scaling requires consistent monthly profits", "News trading has restrictions", "Maximum position limits based on level"],
        spreadType: "Raw Spreads"
    },
    {
        id: "20",
        name: "True Forex Funds",
        slug: "true-forex-funds",
        logo: "/logos/truefx.png",
        rating: 4.3,
        reviewCount: 420,
        maxFunding: "$400,000",
        profitSplit: "80%",
        evaluationType: "2-Step",
        priceStarting: 59,
        features: ["Affordable Entry", "2-Step Evaluation", "Multiple Platforms"],
        description: "Budget-friendly prop firm with one of the lowest entry prices in the industry starting at just $59.",
        pros: ["Very affordable (from $59)", "Multiple platform options", "No time limits", "Good for beginners"],
        cons: ["80% profit split", "Less established", "Basic dashboard"],
        fullReview: "True Forex Funds offers one of the most affordable entry points in the prop firm industry. Their 2-step evaluation starts at just $59, making them accessible to traders on a budget. They support multiple trading platforms and have no time limits on their challenges.",
        affiliateUrl: "https://trueforexfunds.com/",
        websiteUrl: "https://trueforexfunds.com/",
        metaTitle: "True Forex Funds Review: $59 Entry Point",
        metaDescription: "True Forex Funds offers the most affordable prop firm challenges. Read our review of their $59 entry option.",
        hiddenRules: ["Consistency score affects profit split", "Maximum daily trades during evaluation", "Lot size limits based on account"],
        spreadType: "Low Spreads"
    },
    {
        id: "21",
        name: "The Trading Pit",
        slug: "the-trading-pit",
        logo: "/logos/tradingpit.png",
        rating: 4.4,
        reviewCount: 350,
        maxFunding: "$5,000,000",
        profitSplit: "80%",
        evaluationType: "2-Step",
        priceStarting: 99,
        features: ["$5M Scaling", "Multi-Asset", "CFD & Futures"],
        description: "Austrian prop firm with massive $5M scaling potential across forex, indices, commodities, and crypto.",
        pros: ["$5M max funding", "Multi-asset trading", "Regulated company", "Professional platform"],
        cons: ["80% profit split", "Strict drawdown", "Complex rules"],
        fullReview: "The Trading Pit is an Austrian-based prop firm offering one of the highest scaling potentials at $5 million. They provide access to forex, indices, commodities, and crypto. Being regulated in Austria adds credibility. Their platform is professional-grade.",
        affiliateUrl: "https://thetradingpit.com/",
        websiteUrl: "https://thetradingpit.com/",
        metaTitle: "The Trading Pit Review: $5M Scaling Potential",
        metaDescription: "The Trading Pit offers up to $5M in funding. Read our review of this Austrian prop firm.",
        hiddenRules: ["Scaling requires specific profit percentages", "Drawdown is equity-based", "Position limits per instrument"],
        spreadType: "Raw + Commission"
    },
    {
        id: "22",
        name: "Lux Trading Firm",
        slug: "lux-trading-firm",
        logo: "/logos/lux.png",
        rating: 4.6,
        reviewCount: 480,
        maxFunding: "$10,000,000",
        profitSplit: "75%",
        evaluationType: "2-Step",
        priceStarting: 299,
        features: ["$10M Max Capital", "Professional Trading", "Elite Program"],
        description: "Premium prop firm targeting professional traders with funding up to $10 million through their Elite Trader program.",
        pros: ["$10M max funding", "Professional environment", "Excellent reputation", "True prop firm model"],
        cons: ["Lower profit split (75%)", "Higher entry cost", "Strict requirements"],
        fullReview: "Lux Trading Firm targets serious, professional traders with their Elite program offering up to $10 million in funding. They operate more like a traditional prop firm with lower profit splits but genuine institutional backing. Their professional approach attracts experienced traders.",
        affiliateUrl: "https://luxtradingfirm.com/",
        websiteUrl: "https://luxtradingfirm.com/",
        metaTitle: "Lux Trading Firm Review: $10M Elite Program",
        metaDescription: "Lux Trading Firm offers institutional-grade funding up to $10M. Read our review of their Elite Trader program.",
        hiddenRules: ["Elite accounts have stricter oversight", "Regular performance reviews required", "Style consistency monitored"],
        spreadType: "Institutional Spreads"
    },
    {
        id: "23",
        name: "Funded Trading Plus",
        slug: "funded-trading-plus",
        logo: "/logos/ftplus.png",
        rating: 4.5,
        reviewCount: 560,
        maxFunding: "$2,500,000",
        profitSplit: "Up to 100%",
        evaluationType: "1-Step",
        priceStarting: 119,
        features: ["1-Step Master", "100% Profit Split", "No Time Limits"],
        description: "Fast-growing prop firm with a simple 1-step evaluation and 100% profit split at higher tiers.",
        pros: ["100% profit split achievable", "Simple 1-step process", "No time limits", "Good scaling plan"],
        cons: ["Newer firm", "Some platform issues reported", "Competitive pricing but not cheapest"],
        fullReview: "Funded Trading Plus has quickly become popular with their 1-step Master program. They offer up to 100% profit split at higher funding levels, which is rare in the industry. Their no time limit policy removes pressure during evaluation.",
        affiliateUrl: "https://fundedtradingplus.com/",
        websiteUrl: "https://fundedtradingplus.com/",
        metaTitle: "Funded Trading Plus Review: 100% Profit Split",
        metaDescription: "Funded Trading Plus offers up to 100% profit split. Read our review of their 1-step Master program.",
        hiddenRules: ["Consistency scoring affects scaling", "News trading limited", "Maximum open positions"],
        spreadType: "Raw Spreads"
    },
    {
        id: "24",
        name: "Goat Funded Trader",
        slug: "goat-funded-trader",
        logo: "/logos/goat.png",
        rating: 4.4,
        reviewCount: 290,
        maxFunding: "$800,000",
        profitSplit: "Up to 95%",
        evaluationType: "1-Step",
        priceStarting: 48,
        features: ["Ultra Low Cost", "1-Step Only", "95% Profit Split"],
        description: "One of the cheapest prop firms in the industry with evaluations starting at just $48.",
        pros: ["Extremely affordable", "Up to 95% profit split", "Simple 1-step", "No minimum days"],
        cons: ["Very new firm", "Limited track record", "Basic support"],
        fullReview: "Goat Funded Trader disrupted the market with their ultra-low pricing, making prop trading accessible to almost anyone. Their 1-step evaluation is straightforward with no minimum trading days. The 95% profit split at higher tiers is competitive.",
        affiliateUrl: "https://goatfundedtrader.com/",
        websiteUrl: "https://goatfundedtrader.com/",
        metaTitle: "Goat Funded Trader Review: $48 Challenges",
        metaDescription: "Goat Funded Trader offers the cheapest prop firm challenges. Read our review of their $48 entry option.",
        hiddenRules: ["Profit split increases with consistency", "Scaling has specific requirements", "Limited instruments during news"],
        spreadType: "Low Spreads"
    },
    {
        id: "25",
        name: "Finotive Funding",
        slug: "finotive-funding",
        logo: "/logos/finotive.png",
        rating: 4.3,
        reviewCount: 210,
        maxFunding: "$400,000",
        profitSplit: "95%",
        evaluationType: "1-Step",
        priceStarting: 79,
        features: ["95% Profit Split", "1-Step Challenge", "Unlimited Time"],
        description: "Budget-friendly prop firm offering 95% profit split with no time limits on their evaluations.",
        pros: ["95% profit split", "Affordable pricing", "No time limits", "Good trading conditions"],
        cons: ["Newer firm", "Smaller community", "Limited payment options"],
        fullReview: "Finotive Funding offers an attractive package with 95% profit split and affordable pricing. Their 1-step challenge has no time limits, removing the pressure to rush trades. Trading conditions are competitive with tight spreads.",
        affiliateUrl: "https://finotivefunding.com/",
        websiteUrl: "https://finotivefunding.com/",
        metaTitle: "Finotive Funding Review: 95% Profit Split",
        metaDescription: "Finotive Funding offers 95% profit split with affordable challenges. Read our complete review.",
        hiddenRules: ["Consistency requirements for higher splits", "Maximum lot sizes", "Geographic restrictions apply"],
        spreadType: "Low Spreads"
    }
]
